
server:
  port: 8080

platform:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/education
    username: admin
    password: adminka
    pool-settings:
      pool-name: "main-pool"
  security:
    stub-details-service:
      users:
        -
          username: admin
          password: adminka
          authorities:
            - ADMIN
    jwt:
      rsa:
        private-key: file:/home/admin/src/java/edu-platform/util/private.key
        public-key: file:/home/admin/src/java/edu-platform/util/public.key