

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1
    environment:
      POSTGRES_DB: "education"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "adminka"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: